# Server Configuration
spring:
  application:
    name: @project.name@

# Context Path Configuration
controller:
  properties:
    base-path: /api/v1

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    use-root-path: true

# OpenAPI Definition
openapi:
  service:
    title: @project.name@
    version: @project.version@
    description: @project.description@
    contact:
      name: Raul Bolivar Navas
      email: rasysbox@hotmail.com

# Logging & Metrics Configuration
logging:
  level:
    org.hibernate: warn
info:
  project-version: @project.version@
  build-timestamp: ${maven.build.timestamp}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      status:
        http-mapping:
          down: 500
      show-details: always
  http exchanges:
    recording:
      include: request-headers,time-taken,session-id