# Server Configuration
server:
  port: 8080

# OpenAPI Definition
openapi:
  service:
    host: http://localhost:8085

spring:

  # Database Configuration
  datasource:
    url: jdbc:postgresql://postgres-rest-template:5432/patterns
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
