version: '3.9'

services:

  # ----------------
  # -- Postgresql --
  # ----------------
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb-telemetry
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: $POSTGRES_TELEMETRY_DB_DATABASE
      POSTGRES_USER: $POSTGRES_TELEMETRY_DB_USER
      POSTGRES_PASSWORD: $POSTGRES_TELEMETRY_DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - public

volumes:
  timescaledb_data:

networks:
  public: